server:
  port: 6001
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka:7001/eureka/,http://eureka2:7002/eureka/
  instance:
    instance-id: myzuul.com

    prefer-ip-address: true
zuul:
  routes:
    user:
      serviceId: provider
      path: /customers/**
  ignored-services: provider
#  ignored-services: "*"
  prefix: /neu

#  AccessTokenFilter:
#    pre:
#      disable: true
#  AccessTokenFilter1:
#    pre:
#      disable: true